name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # O el nombre de tu rama principal
  pull_request:
    branches:
      - main  # O el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest  # Usa una máquina virtual de Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Ajusta la versión de Python a la que necesites

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test  # Si tienes pruebas configuradas

    - name: Deploy to production
      if: github.ref == 'refs/heads/main'  # Solo se ejecuta en la rama principal
      run: |
        # Aquí iría tu script de despliegue, por ejemplo:
        # ssh user@host 'cd /path/to/your/project && git pull && docker-compose up'
